language: java

matrix:
  include:
    - env: DATABASE=hsql
    - env: DATABASE=mysql
      services: myql
      before_install: mysql -e 'CREATE DATABASE myapp_test;'
    - env: DATABASE=oracle

script: "mvn test -Duser.name=$DATABASE"
