language: java

cache:
  directories:
    - "$HOME/.m2/repository"

matrix:
  include:
    - env: DATABASE=hsql
    - env: DATABASE=mysql
      services: mysql
      before_install: mysql -e 'CREATE DATABASE test;'
    - env: DATABASE=oracle
      services: docker
      before_install:
      - docker run --name oracle -d -p 1521:1521 sath89/oracle-xe-11g
      - docker ps -a
      - docker exec -i oracle bash -c 'until echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE \n select 1 from dual;" | sqlplus -s system/oracle > /dev/null; do echo "Waiting for Oracle XE to start...($(date))"; sleep 15; done'


script: "mvn -B test -Duser.name=$DATABASE"
