language: java

cache:
  directories:
    - "$HOME/.m2/repository"

matrix:
  include:
    - env: DATABASE=hsql
    - env: DATABASE=mysql
      services: mysql
      before_install: mysql -e 'CREATE DATABASE test;'
    #- env: DATABASE=oracle

script: "mvn -B test -Duser.name=$DATABASE"
